### ISSUE TITLE
Module won't compile

### ISSUE THREAD

**Issue by ghost** [fim/icapclient3#1]
Trying to compile icapclient3 on Debian 9 (64bit) fails:

    # python3 setup.py build
    running build
    running build_ext
    building 'icapclient' extension
    creating build
    creating build/temp.linux-x86_64-3.5
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fdebug-prefix-map=/build/python3.5-MLq5fN/python3.5-3.5.3=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.5m -c icapclient.c -o build/temp.linux-x86_64-3.5/icapclient.o -std=gnu99 -Wextra -D_REENTRANT -g -O2 -fdebug-prefix-map=/build/c-icap-0.4.4=. -fPIE -fstack-protector-strong -Wformat -Werror=format-security -Wall -Wall -D_FILE_OFFSET_BITS=64 -I/usr/include -I/usr/include/c_icap
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fdebug-prefix-map=/build/python3.5-MLq5fN/python3.5-3.5.3=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.5m -c ICAPConnection.c -o build/temp.linux-x86_64-3.5/ICAPConnection.o -std=gnu99 -Wextra -D_REENTRANT -g -O2 -fdebug-prefix-map=/build/c-icap-0.4.4=. -fPIE -fstack-protector-strong -Wformat -Werror=format-security -Wall -Wall -D_FILE_OFFSET_BITS=64 -I/usr/include -I/usr/include/c_icap
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fdebug-prefix-map=/build/python3.5-MLq5fN/python3.5-3.5.3=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.5m -c ICAPResponse.c -o build/temp.linux-x86_64-3.5/ICAPResponse.o -std=gnu99 -Wextra -D_REENTRANT -g -O2 -fdebug-prefix-map=/build/c-icap-0.4.4=. -fPIE -fstack-protector-strong -Wformat -Werror=format-security -Wall -Wall -D_FILE_OFFSET_BITS=64 -I/usr/include -I/usr/include/c_icap
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fdebug-prefix-map=/build/python3.5-MLq5fN/python3.5-3.5.3=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.5m -c cicap_compat.c -o build/temp.linux-x86_64-3.5/cicap_compat.o -std=gnu99 -Wextra -D_REENTRANT -g -O2 -fdebug-prefix-map=/build/c-icap-0.4.4=. -fPIE -fstack-protector-strong -Wformat -Werror=format-security -Wall -Wall -D_FILE_OFFSET_BITS=64 -I/usr/include -I/usr/include/c_icap
    creating build/lib.linux-x86_64-3.5
    x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,relro -g -fdebug-prefix-map=/build/python3.5-MLq5fN/python3.5-3.5.3=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.5/icapclient.o build/temp.linux-x86_64-3.5/ICAPConnection.o build/temp.linux-x86_64-3.5/ICAPResponse.o build/temp.linux-x86_64-3.5/cicap_compat.o -o build/lib.linux-x86_64-3.5/icapclient.cpython-35m-x86_64-linux-gnu.so -L/usr/lib/x86_64-linux-gnu/ -licapapi
    /usr/bin/ld: build/temp.linux-x86_64-3.5/icapclient.o: relocation R_X86_64_PC32 against undefined symbol `_Py_NoneStruct' can not be used when making a shared object; recompile with -fPIC
    /usr/bin/ld: final link failed: Bad value
    collect2: error: ld returned 1 exit status
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

However, all package requirements seem to be satisfied:

    # dpkg -l | grep icap
    ii  libicapapi-dev                1:0.4.4-1                      amd64        ICAP API library development files
    ii  libicapapi4                   1:0.4.4-1                      amd64        ICAP API library

    # dpkg -l | grep python3-dev
    ii  libpython3-dev:amd64          3.5.3-1                        amd64        header files and a static library for Python (default)
    ii  python3-dev                   3.5.3-1                        amd64        header files and a static library for Python (default)

Output of  `uname -a`:

    Linux machine 4.9.0-6-amd64 #1 SMP Debian 4.9.88-1+deb9u1 (2018-05-07) x86_64 GNU/Linux

Could you point me in the right direction? Thanks in advance.

**Comment by ghost** [comment]
Update:

Module seems to compile and works by running the following commands:

    root@machine:/tmp/pyicapclient/icapclient3-1.1.1# x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.5m -c icapclient.c -o build/temp.linux-x86_64-3.5/icapclient.o -std=gnu99 -Wextra -fPIC -D_REENTRANT -g -O2 -fdebug-prefix-map=/build/c-icap-0.4.4=. -fstack-protector-strong -Wformat -Werror=format-security -Wall -Wall -D_FILE_OFFSET_BITS=64 -I/usr/include -I/usr/include/c_icap
    root@machine:/tmp/pyicapclient/icapclient3-1.1.1# x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.5m -c ICAPConnection.c -o build/temp.linux-x86_64-3.5/ICAPConnection.o -std=gnu99 -Wextra -fPIC -D_REENTRANT -g -O2 -fdebug-prefix-map=/build/c-icap-0.4.4=. -fPIC -fstack-protector-strong -Wformat -Werror=format-security -Wall -Wall -D_FILE_OFFSET_BITS=64 -I/usr/include -I/usr/include/c_icap
    root@machine:/tmp/pyicapclient/icapclient3-1.1.1# x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.5m -c ICAPResponse.c -o build/temp.linux-x86_64-3.5/ICAPResponse.o -std=gnu99 -Wextra -fPIC -D_REENTRANT -g -O2 -fdebug-prefix-map=/build/c-icap-0.4.4=. -fPIC -fstack-protector-strong -Wformat -Werror=format-security -Wall -Wall -D_FILE_OFFSET_BITS=64 -I/usr/include -I/usr/include/c_icap
    root@machine:/tmp/pyicapclient/icapclient3-1.1.1# x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.5m -c cicap_compat.c -o build/temp.linux-x86_64-3.5/cicap_compat.o -std=gnu99 -Wextra -fPIC -D_REENTRANT -g -O2 -fdebug-prefix-map=/build/c-icap-0.4.4=. -fPIC -fstack-protector-strong -Wformat -Werror=format-security -Wall -Wall -D_FILE_OFFSET_BITS=64 -I/usr/include -I/usr/include/c_icap
    root@machine:/tmp/pyicapclient/icapclient3-1.1.1# x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,relro -fPIC -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.5/icapclient.o build/temp.linux-x86_64-3.5/ICAPConnection.o build/temp.linux-x86_64-3.5/ICAPResponse.o build/temp.linux-x86_64-3.5/cicap_compat.o -o build/lib.linux-x86_64-3.5/icapclient.cpython-35m-x86_64-linux-gnu.so -L/usr/lib/x86_64-linux-gnu/ -licapapi

    root@machine:/tmp/pyicapclient/icapclient3-1.1.1/build# cd ..
    root@machine:/tmp/pyicapclient/icapclient3-1.1.1# python3 setup.py build
    running build
    running build_ext
    root@machine:/tmp/pyicapclient/icapclient3-1.1.1# python3 setup.py install
    running install
    running build
    running build_ext
    running install_lib
    copying build/lib.linux-x86_64-3.5/icapclient.cpython-35m-x86_64-linux-gnu.so -> /usr/local/lib/python3.5/dist-packages
    running install_egg_info
    Writing /usr/local/lib/python3.5/dist-packages/icapclient3-1.1.1.egg-info

It looks like the compiler and linker calls need to be updated in order to really use `-fPIC` instead of `-fPIE`.

**Comment by fim** [comment]
Hm, something seems off. We don't specify the `-fPIC` or `-fPIE` explicitly, rather we let distutils figure it out on its own (as explained here: https://docs.python.org/3/extending/building.html), which I tested locally and it worked. 

Can you run the following commands and report back:

 * `$ c-icap-libicapapi-config --cflags`
 * `$ c-icap-libicapapi-config --libs`
 * `$ x86_64-linux-gnu-gcc --version`
 * `python -c 'import distutils; print(distutils.sys.version)'`

Thanks!

**Comment by ghost** [comment]
Thanks. Will do so and report back.

**Comment by ghost** [comment]
This is the output of the commands:

    root@machine:~# c-icap-libicapapi-config --cflags
    -D_REENTRANT -g -O2 -fdebug-prefix-map=/build/c-icap-0.4.4=. -fPIE -fstack-protector-strong -Wformat -Werror=format-security -Wall -Wall -D_FILE_OFFSET_BITS=64 -I/usr/include -I/usr/include/c_icap

    root@machine:~# c-icap-libicapapi-config --libs
    -L/usr/lib/x86_64-linux-gnu/ -licapapi

    root@machine:~# x86_64-linux-gnu-gcc --version
    x86_64-linux-gnu-gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516
    Copyright (C) 2016 Free Software Foundation, Inc.
    This is free software; see the source for copying conditions.  There is NO
    warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

    root@machine:~# python -c 'import distutils; print(distutils.sys.version)'
    2.7.13 (default, Nov 24 2017, 17:33:09) 
    [GCC 6.3.0 20170516]

**Comment by ghost** [comment]
`- ping -`

**Comment by TomskDiver** [comment]
same error on Ubuntu 18.04.1 LTS (Bionic Beaver)

**Comment by fim** [comment]
Somehow I never got github notifications for updates for this issue. I apologise for the delay in response but I had a quick look today and I think that it's due to `c-icap-libicapapi-config` specifying `-fPIE` which breaks the build.

I did a quick fix (#3) by simply removing `-fPIE` from the cflags and tested the fix with ubuntu and debian and both seem to work.
